server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-request-db
    username: postgres
    password: 230902
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/