apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tracking-deployment
  labels:
    app: ms-tracking-deployment
spec:
  selector:
    matchLabels:
      app: ms-tracking-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tracking-deployment
    spec:
      containers:
        - name: ms-tracking
          image: reii23/ms-tracking
          ports:
            - containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_TRACKING
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_TRACKING
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_NAME_TRACKING
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
